spring:
  devtools:
    restart:
      exclude: templates/**, static/**
  profiles:
    active: dev
  jpa:
    database: MYSQL
    # 是否显示HQL
    show-sql: true
    hibernate:
      # Entity与数据库表名对应
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        # 数据库方言
        dialect: org.hibernate.dialect.MySQL5Dialect
        # 是否显示统计信息
        generate_statistics: flase
        # Hibernate二级缓存和Query缓存
        cache:
          # 二级缓存
          use_second_level_cache: true
          # Query 缓存
          use_query_cache: true
          region:
            # 使用Ehcache
            factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
        # Spring Boot 整合Hibernate
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext

  jackson:
    default-property-inclusion: non_null
  #thymeleaf
  thymeleaf:
    mode: HTML
    suffix: .html
    prefix: classpath:/templates/
  #session会话存储类型
  session:
    store-type: redis

  #redis config
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    pool:
      min-idle: 1
    timeout: 3000
  ##kafa
  kafka:
    bootstrap-servers: 120.0.0.1:9092
    consumer:
      group-id: xunwu

logging:
  level:
    org:
      hibernate:
        SQL: debug
  pattern:
    level: debug
#关闭HTTP基本验证
security:
  basic:
    enabled: false

server:
  error:
    whitelabel:
      enabled: false


#qiniu
qiniu:
  AccessKey: hACZr9SVm1skGkWNYJW4tXbdBw2Ae03uuaGyysyA
  SecretKey: eE3nabE5p8Et2_XT8TNTVhZ3VLd0t4n8S6uXbXxM
  Bucket: bestzhu
  cdn:
    prefix: pe4jarqs1.bkt.clouddn.com



